platform :ios, '13.0'

use_frameworks! :linkage => :static
use_modular_headers!

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_application_path = '../.flutter-plugins'
  eval(File.read(File.join(flutter_application_path, 'podhelper.rb')), binding)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
